### ISSUE TITLE
deploy stage failure - S3 ACL error

### ISSUE THREAD

**Issue by SnikSec** [aws-samples/amazon-omics-webapp-integrations#23]
Getting a failure due to ACL updates for S3 in April of 2023. documentation available [here](https://stackoverflow.com/questions/70645117/enable-s3-acl-access-for-cloudfront-logs). This change implements an error where due to the ownership condition not being described in the CFT, it results in the following error message and triggers a rollback (during Cloudfront stage)

`Resource handler returned message: "Invalid request provided: AWS::CloudFront::Distribution: The S3 bucket that you specified for CloudFront logs does not enable ACL access: jmware-dev-omics-app-demo-jmwaredevomicsappdemofro-p4b8iscb2gjs.s3.us-east-1.amazonaws.com (Service: CloudFront, Status Code: 400, Request ID: 129d32b3-bc31-4a36-b3eb-4b09958acf57)" (RequestToken: fe55cd63-1eb5-d3a5-9ddf-de8a97c0141d, HandlerErrorCode: InvalidRequest)`

To resolve this, we need to add a property to the CFT:

```
"OwnershipControls": {
                    "Rules": [
                        {
                            "ObjectOwnership": "BucketOwnerEnforced"
                        }
                    ]
                }
```

As outlined in the AWS documentation [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-ownershipcontrols.html).

I've attempted to manually update the CFT in the _tree.json_ file as well as _.nested.template.json_ file for the frontend deployment however, it is overridden as apart of the run and Im not sure from where to update the source.

**Comment by Hidenori14** [comment]
@Hero104FH 
Thank you for your notice.
The default branch fixed this failure, so please try to deploy it.
