### ISSUE TITLE
getting error when trying to install - IAM entity contains wildcard permissions and does not have a cdk-nag rule

### ISSUE THREAD

**Issue by datnoor** [aws-samples/amazon-omics-webapp-integrations#34]
[Error at /ctx-dev-hcls-dev-omics-app-infraStack/ctx-dev-hcls-dev-omics-app-infraStack-application/LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/ServiceRole/DefaultPolicy/Resource] AwsSolutions-IAM5[Resource::*]: The IAM entity contains wildcard permissions and does not have a cdk-nag rule suppression with evidence for those permission.

Log file below: 

>>npm run deployInfra

> omics-webapp@1.0.0 deployInfra
> cdk deploy --app 'npx ts-node --prefer-ts-exts bin/infra.ts'

Bundling asset ctx-dev-hcls-dev-omics-app-infraStack/ctx-dev-hcls-dev-omics-app-infraStack-application/ctx-dev-hcls-dev-omics-app-infraStack-application-listOmicsJob/ctx-dev-hcls-dev-omics-app-infraStack-application-listOmicsJob-nodejslambda/Code/Stage...

  ../../../cdk.out/bundling-temp-4b45d503f52d8160c15210264be42061e7027e6dbf0cb413d9abaf5eca35f9f1/index.js  4.5kb

⚡ Done in 10ms

added 79 packages, and audited 80 packages in 506ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Bundling asset ctx-dev-hcls-dev-omics-app-infraStack/ctx-dev-hcls-dev-omics-app-infraStack-application/ctx-dev-hcls-dev-omics-app-infraStack-application-mutationOmics/ctx-dev-hcls-dev-omics-app-infraStack-application-mutationOmics-nodejslambda/Code/Stage...

  ../../../cdk.out/bundling-temp-4a544159e409166a4fdd71f05450c50823ed4570da3af561f19d2baab8594568/index.js  3.1kb

⚡ Done in 2ms

added 79 packages, and audited 80 packages in 523ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Bundling asset ctx-dev-hcls-dev-omics-app-infraStack/ctx-dev-hcls-dev-omics-app-infraStack-application/ctx-dev-hcls-dev-omics-app-infraStack-application-manipulationEcr/ctx-dev-hcls-dev-omics-app-infraStack-application-manipulationEcr-nodejslambda/Code/Stage...

  ../../../cdk.out/bundling-temp-afd874fc44cf7cbc722fb11af32947dc1613250cc921b8370f0469ad3aa01748/index.js  2.8kb

⚡ Done in 2ms

added 79 packages, and audited 80 packages in 478ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[WARNING] aws-cdk-lib.aws_appsync.GraphqlApiProps#schema is deprecated.
  use Definition.schema instead
  This API will be removed in the next major release.
[Warning at /ctx-dev-hcls-dev-omics-app-infraStack/ctx-dev-hcls-dev-omics-app-infraStack-application/ctx-dev-hcls-dev-omics-app-infraStack-application-listOmicsJob] If you are relying on AWS SDK v2 to be present in the Lambda environment already, please explicitly configure a NodeJS runtime of Node 16 or lower. [ack: @aws-cdk/aws-lambda-nodejs:sdkV2NotInRuntime]
[Warning at /ctx-dev-hcls-dev-omics-app-infraStack/ctx-dev-hcls-dev-omics-app-infraStack-application/ctx-dev-hcls-dev-omics-app-infraStack-application-mutationOmics] If you are relying on AWS SDK v2 to be present in the Lambda environment already, please explicitly configure a NodeJS runtime of Node 16 or lower. [ack: @aws-cdk/aws-lambda-nodejs:sdkV2NotInRuntime]
[Warning at /ctx-dev-hcls-dev-omics-app-infraStack/ctx-dev-hcls-dev-omics-app-infraStack-application/ctx-dev-hcls-dev-omics-app-infraStack-application-manipulationEcr] If you are relying on AWS SDK v2 to be present in the Lambda environment already, please explicitly configure a NodeJS runtime of Node 16 or lower. [ack: @aws-cdk/aws-lambda-nodejs:sdkV2NotInRuntime]
[Error at /ctx-dev-hcls-dev-omics-app-infraStack/ctx-dev-hcls-dev-omics-app-infraStack-application/LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/ServiceRole/DefaultPolicy/Resource] AwsSolutions-IAM5[Resource::*]: The IAM entity contains wildcard permissions and does not have a cdk-nag rule suppression with evidence for those permission.

Found error

**Comment by Hidenori14** [comment]
@datnoor 
Fix the cdk-nag error in v1.0.1, so please check if your environment resolve the problem as well.
