### ISSUE TITLE
How do I launch the webapp?

### ISSUE THREAD

**Issue by wshands** [aws-samples/amazon-omics-webapp-integrations#42]
I have successfully deployed the webapp frontend and infrastructure using 'npm run deployAll' but I don't see the UI. How do I start the UI? There is nothing in the README that I saw. Is the UI supposed to come up after deploy?

Thanks!

**Comment by Hidenori14** [comment]
You can see the uri after deployment like this or CloudFront page. You can access to the web app.
Also I will add it to the README.
```
Outputs:
xxx-dev-omics-app-frontendStack.cloudfrontdomain = xxxx.net
```

**Comment by Hidenori14** [comment]
Add the output example to README by #44
