### ISSUE TITLE
On npm run deployAll I get Cannot find module './types/type'

### ISSUE THREAD

**Issue by wshands** [aws-samples/amazon-omics-webapp-integrations#45]
When I do 'npm run deployAll'  I am seeing:
TSError: ⨯ Unable to compile TypeScript:
config.ts:1:28 - error TS2307: Cannot find module './types/type' or its corresponding type declarations.

1 import { BaseConfig } from './types/type';
                             ~~~~~~~~~~~~~~

How do I fix this?

Thanks!

**Comment by Hidenori14** [comment]
Add the types to fix it.
Could you check it?
Thanks.

**Comment by wshands** [comment]
I don't see the package here https://www.npmjs.com/search?q=types%2Ftype. Can you suggest command line for adding the types?

**Comment by Hidenori14** [comment]
@wshands 
Not npm package but [the original type](https://github.com/aws-samples/amazon-omics-webapp-integrations/blob/main/types/type.d.ts) in this repo.
Therefore, could you pull the main branch to update it at first and then try to deploy command?

**Comment by wshands** [comment]
Yes that worked thanks!
